# Generated by Django 4.2.3 on 2023-07-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
                ('json_file', models.FileField(upload_to='json_files/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
